In [1]:
import numpy as np

### Задание 1

In [2]:
a = np.array([[1, 6], 
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = a.mean(axis = 0)

In [7]:
mean_a

array([2. , 8.4])

### Задание 2

In [9]:
a_centered = a - mean_a

In [10]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [17]:
a_centered[:,1:2]

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [32]:
a_centered_sp = np.dot(a_centered[:,0:1].reshape(a.shape[0]), 
                       a_centered[:,1:2].reshape(a.shape[0]))
a_centered_sp

8.0

In [33]:
a_centered_sp / (a.shape[0] - 1)

2.0

### Задание 4

In [36]:
np.cov(a.transpose())[0, 1]

2.0